### ISSUE TITLE
Server log error Waila plugin

### ISSUE THREAD

**Issue by xanthian** [ConsistencyPlus/ConsistencyPlus#78]
[main/ERROR]: Error creating instance of plugin consistency_plus:plugin
java.lang.RuntimeException: Cannot load class io.github.consistencyplus.consistency_plus.core.ConsistencyPlusWailaPlugin in environment type SERVER
	at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.plugin.PluginLoader.createPlugin(PluginLoader.java:20) ~[wthit-fabric-3.10.0.jar:?]
	at mcp.mobius.waila.fabric.FabricPluginLoader.gatherPlugins(FabricPluginLoader.java:60) ~[wthit-fabric-3.10.0.jar:?]
	at mcp.mobius.waila.plugin.PluginLoader.initialize(PluginLoader.java:36) ~[wthit-fabric-3.10.0.jar:?]
	at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:65) ~[wthit-fabric-3.10.0.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) [fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]

MC 1.17.1
fabric-api-0.41.3+1.17

**Comment by Cart3r1234** [comment]
Closing this since it will be part of 0.4.2pr1
